[package]
name = "wasm-quickjs"
version = "0.0.1"
authors = ["aranajhonny <jhonnyjosearana@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lucet-runtime = "0.1.1"
lucet-wasi = "0.1.1"